net_name: "vit-s+16"
num_experts: 16
router_k: 4
dist_loss_weight: 1.0
s2_loss_weight: 0.16
load_balance_loss_weight: 1
embedding_dim: 512
freeze_weights: false
dataset_dir: "/Users/pepijnvanwijk/Documents/projects/geoGuessrV2/createDataset/finalDataset"
log_interval: 100
seed: 123
epochs: 30
optimizer: "adamW"
learning_rate: 0.00025
beta_2: 0.999
weight_decay: 0.01
# batch_size: 64
batch_size: 16
gradient_clipping_norm: 4.0
early_stop: 3
run_name: "test-nogeohead-diff-loadbalancingloss-0.00025lr-1xdistloss-long"
s2_cell_level: 7
pretrained_path: ""
