net_name: "convnext-tiny"
freeze_weights: false
dataset_dir: "dataset/"
log_interval: 10
seed: 123
epochs: 2
optimizer: "adamW"
learning_rate: 0.00005
beta_2: 0.98
weight_decay: 0.05
batch_size: 64
gradient_clipping_norm: 1.0
early_stop: 3
run_name: "convnext-tiny"
