net_name: "vit-l16"
num_experts: 8
router_k: 2
dist_loss_weight: 2.0
s2_loss_weight: 0.16
load_balance_loss_weight: 1
embedding_dim: 512
freeze_weights: false
dataset_dir: "dataset"
log_interval: 200
seed: 123
epochs: 16
optimizer: "adamW"
learning_rate: 0.00005
beta_2: 0.999
weight_decay: 0.005
batch_size: 64
gradient_clipping_norm: 4.0
early_stop: 3
run_name: "final_run_3_optimlr"
s2_cell_level: 7
pretrained_path: ""
